export enum ErrorCode {
  CAN_NOT_LOGIN = 'Can not login',
  REFRESH_TOKEN_WRONG = 'Refresh token wrong',
  USER_HAS_BANNED = 'USER_HAS_BANNED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WRONG_PASSWORD = 'Wrong old password',
  HAVE_EMAIL = 'Email already exists',
  HAVE_USERNAME = 'Username already exists',
  MISSING_PASSWORD = 'MISSING_PASSWORD',

  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_SLUG_ALREADY_EXISTS = 'ROLE_SLUG_ALREADY_EXISTS',
  CAN_NOT_DELETE_ROLE = 'Can not delete role default',
  CAN_NOT_EDIT_ROLE = 'Can not edit role default',
  ROLE_HAS_USER = 'ROLE_HAS_USER',
  ROLE_PERMISSION_OVER_PARENT = 'ROLE_PERMISSION_OVER_PARENT',

  CAN_NOT_DELETE_YOURSELF = 'CAN_NOT_DELETE_YOURSELF',
  CAN_NOT_BAN_YOURSELF = 'CAN_NOT_BAN_YOURSELF',

  WORKER_NOT_FOUND = 'WORKER_NOT_FOUND',
  AGENT_NOT_FOUND = 'AGENT_NOT_FOUND',
  AGENT_IN_USE = 'AGENT_IN_USE',

  NENKIN_PROCEDURE_NOT_FOUND = 'NENKIN_PROCEDURE_NOT_FOUND',
  NENKIN_DOCUMENT_NOT_FOUND = 'NENKIN_DOCUMENT_NOT_FOUND',
  NENKIN_TEMPLATE_NOT_CONFIGURED = 'NENKIN_TEMPLATE_NOT_CONFIGURED',
  NENKIN_FIRST_REQUIRED = 'NENKIN_FIRST_REQUIRED',
  WORKER_INFO_INCOMPLETE = 'WORKER_INFO_INCOMPLETE',

  FILE_REQUIRED = 'FILE_REQUIRED',
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',
  POSTAL_CODE_INVALID = 'POSTAL_CODE_INVALID',
  POSTAL_CODE_LOOKUP_FAILED = 'POSTAL_CODE_LOOKUP_FAILED',

  OCR_NOT_CONFIGURED = 'OCR_NOT_CONFIGURED',
  OCR_NO_DOCUMENT = 'OCR_NO_DOCUMENT',
  OCR_IMAGE_NOT_FOUND = 'OCR_IMAGE_NOT_FOUND',
  OCR_IMAGE_NOT_SUPPORTED = 'OCR_IMAGE_NOT_SUPPORTED',
  OCR_EMPTY_RESULT = 'OCR_EMPTY_RESULT',
  OCR_RATE_LIMITED = 'OCR_RATE_LIMITED',
  OCR_PROVIDER_ERROR = 'OCR_PROVIDER_ERROR',
}
