export enum ErrorCode {
  CAN_NOT_LOGIN = 'Can not login',
  REFRESH_TOKEN_WRONG = 'Refresh token wrong',
  USER_HAS_BANNED = 'USER_HAS_BANNED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WRONG_PASSWORD = 'Wrong old password',
  HAVE_EMAIL = 'Email already exists',
  HAVE_USERNAME = 'Username already exists',
  MISSING_PASSWORD = 'MISSING_PASSWORD',

  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_SLUG_ALREADY_EXISTS = 'ROLE_SLUG_ALREADY_EXISTS',
  CAN_NOT_DELETE_ROLE = 'Can not delete role default',
  CAN_NOT_EDIT_ROLE = 'Can not edit role default',
  ROLE_HAS_USER = 'ROLE_HAS_USER',
  ROLE_PERMISSION_OVER_PARENT = 'ROLE_PERMISSION_OVER_PARENT',

  CAN_NOT_DELETE_YOURSELF = 'CAN_NOT_DELETE_YOURSELF',
  CAN_NOT_BAN_YOURSELF = 'CAN_NOT_BAN_YOURSELF',
}
